In [160]:
import numpy as np
import random
import time
t1 = np.array([1,2,3])
t2 = np.array([1.3,2.6,3.12])
# 这样array传参只能传入数组或者单个参数
# t3 = np.array(1,2,3,4)
print(t1)
print(type(t1))
print(t1.dtype)
print(t2.dtype)
#print(t3)
t3 = np.array([(1.5,2,3),(2,3,1)])
print(t3)

a= np.array([[1,2],[3,4]],dtype=complex)
print(a)
b=np.zeros((3,4))
print(b)

c=np.arange(12)
print(c)
print(t2.dtype)

d=np.array(range(2),dtype="float64")
print(d)
# 转换类型
d.astype("i1")
print(d)

#取小数
a1 = np.round([random.random() for i in range(10)],2)
print(a1)

#获取数组形状,有几个数代表是个几维数组
#reshape代表重新设置数组
t1 = np.arange(14)
#t1.shape
t1.reshape(2,7)
t1.reshape(14,)

#矩阵相乘 使用@或者dot
j1=np.array([[1,2],[3,4]])
j2=np.array([[5,6],[7,8]])
j1.dot(j2)

[1 2 3]
<class 'numpy.ndarray'>
int32
float64
[[1.5 2.  3. ]
 [2.  3.  1. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
float64
[0. 1.]
[0. 1.]
[0.22 0.75 0.66 0.18 0.54 0.12 0.75 0.28 0.08 0.9 ]


array([[19, 22],
       [43, 50]])

In [173]:
a=np.ones((2,3),dtype=int)
b = np.random.random((2,3))
a *= 3
a.sum()
a.min()
a.sum(axis=0)
j2=np.array([[5,6],[7,8]])
#获取每一列上的最小值， axis=1的时候获取每一行上最小值
j2.min(axis=0)
#获取e次方
np.exp(a)
#获取平方根
np.sqrt(a)

array([[1.73205081, 1.73205081, 1.73205081],
       [1.73205081, 1.73205081, 1.73205081]])