In [2]:
import numpy as np
import random
import time
t1 = np.array([1,2,3])
t2 = np.array([1.3,2.6,3.12])
# 这样array传参只能传入数组或者单个参数
# t3 = np.array(1,2,3,4)
print(t1)
print(type(t1))
print(t1.dtype)
print(t2.dtype)
#print(t3)
t3 = np.array([(1.5,2,3),(2,3,1)])
print(t3)

a= np.array([[1,2],[3,4]],dtype=complex)
print(a)
b=np.zeros((3,4))
print(b)

c=np.arange(12)
print(c)
print(t2.dtype)

d=np.array(range(2),dtype="float64")
print(d)
# 转换类型
d.astype("i1")
print(d)

#取小数
a1 = np.round([random.random() for i in range(10)],2)
print(a1)

[1 2 3]
<class 'numpy.ndarray'>
int32
float64
[[1.5 2.  3. ]
 [2.  3.  1. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
float64
[0. 1.]
[0. 1.]
[0.79 0.68 0.01 0.92 0.75 0.83 0.87 0.7  0.84 0.45]
[1 2 3]
<class 'numpy.ndarray'>
int32
float64
[[1.5 2.  3. ]
 [2.  3.  1. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
float64
[0. 1.]
[0. 1.]
[0.06 0.28 0.11 0.22 0.38 0.19 0.   0.65 0.06 0.65]
